---
version: "3.9"
services:
  backend:
    image: python:3.8.5
    working_dir: /app
    command: ["./run.sh"]
    volumes:
      - ./backend:/app:delegated
    environment:
      - DB_SCHEMA=rtmis
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DEBUG=True
      - DJANGO_SECRET=local-secret
      - APK_UPLOAD_SECRET
      - STORAGE_PATH
      - SENTRY_DSN
    depends_on:
      - db
  worker:
    image: python:3.8.5
    working_dir: /app
    command: ["./run_worker.sh"]
    volumes:
      - ./backend:/app:delegated
    environment:
      - DB_SCHEMA=rtmis
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DEBUG=True
      - DJANGO_SECRET=local-secret
      - APK_UPLOAD_SECRET
      - STORAGE_PATH
      - SENTRY_DSN
    depends_on:
      - backend
  frontend:
    image: akvo/akvo-node-17-alpine:20220121.024749.f30b815
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    depends_on:
      - backend
  db:
    image: postgres:12-alpine
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
volumes:
  pg-data:
