---
version: "3.9"
services:
  backend:
    image: eu.gcr.io/akvo-lumen/rtmis/backend:latest
    working_dir: /app/backend
    volumes:
      - ./:/app:delegated
      - ${SERVICE_ACCOUNT}:/credentials/:ro
    environment:
      - DB_SCHEMA=rtmis
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DJANGO_SECRET=ci-secret
      # env vars for coveralls
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN:-}
      - SEMAPHORE=${SEMAPHORE:-}
      - SEMAPHORE_JOB_ID=${SEMAPHORE_JOB_ID:-}
      - SEMAPHORE_WORKFLOW_ID=${SEMAPHORE_WORKFLOW_ID:-}
      - SEMAPHORE_GIT_PR_NUMBER=${SEMAPHORE_GIT_PR_NUMBER:-}
      - DEBUG=True
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/rtmis-service-account.json
      - MAILJET_APIKEY=$MAILJET_APIKEY
      - MAILJET_SECRET=$MAILJET_SECRET
      - WEBDOMAIN=notset
      - APK_UPLOAD_SECRET=ci-secret
      - STORAGE_PATH="./storage"
    depends_on:
      - db
    command: tail -f /dev/null
  db:
    image: postgres:12-alpine
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
