---
version: "3.9"
services:
  mainnetwork:
    image: alpine:3.14
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 3000:3000
      - 8000:8000
      - 5050:5050
      # backend debuger port
      - 8888:8888
  frontend:
    network_mode: service:mainnetwork
    volumes:
      - ${STORAGE_PATH}/images:/app/public/images:delegated
      - ${STORAGE_PATH}/datapoints:/app/public/datapoints:delegated
      - ${STORAGE_PATH}/apk:/app/public/apk:delegated
      - ${STORAGE_PATH}/master_data:/app/public/master_data:delegated
  worker:
    volumes:
      - ../akvo-config/k8s-secrets/test/rtmis:/credentials/:ro
      - ${STORAGE_PATH}:/app/storage:delegated
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/rtmis-service-account.json
      - MAILJET_APIKEY=$MAILJET_APIKEY
      - MAILJET_SECRET=$MAILJET_SECRET
      - WEBDOMAIN=http://localhost:3000
  backend:
    volumes:
      - ../akvo-config/k8s-secrets/test/rtmis:/credentials/:ro
      - ${STORAGE_PATH}:/app/storage:delegated
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/rtmis-service-account.json
      - MAILJET_APIKEY=$MAILJET_APIKEY
      - MAILJET_SECRET=$MAILJET_SECRET
      - WEBDOMAIN=$WEBDOMAIN
    network_mode: service:mainnetwork
  pgadmin:
    image: dpage/pgadmin4:5.7
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=dev@akvo.org
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - db
    network_mode: service:mainnetwork
volumes:
  pg-admin-data:
