---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmis
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      run: rtmis
  template:
    metadata:
      labels:
        run: rtmis
        rtmis-version: "${CI_COMMIT}"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: frontend
          image: eu.gcr.io/akvo-lumen/rtmis/frontend:${CI_COMMIT}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
          volumeMounts:
            - name: nfs-pvc
              mountPath: "/usr/share/nginx/html/storage"
        - name: cloud-sql-proxy
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "768Mi"
          # https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#run_the_as_a_sidecar
          # It is recommended to use the latest version of the Cloud SQL proxy
          # Make sure to update on a regular schedule!
          image: eu.gcr.io/cloudsql-docker/gce-proxy:1.30.1
          command:
            - "/cloud_sql_proxy"

            # By default, the proxy will write all logs to stderr. In some
            # environments, anything printed to stderr is consider an error. To
            # disable this behavior and write all logs to stdout (except errors
            # which will still go to stderr), use:
            - "-log_debug_stdout"

            - "-instances=$(GOOGLE_PROJECT):$(GOOGLE_SQL_COMPUTE_ZONE):$(GOOGLE_SQL_DB_INSTANCE)=tcp:5432"
            - "-credential_file=/secrets/cloudsql/credentials.json"
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          env:
            - name: GOOGLE_SQL_COMPUTE_ZONE
              valueFrom:
                configMapKeyRef:
                  name: rtmis
                  key: google-sql-compute-zone
            - name: GOOGLE_SQL_DB_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: rtmis
                  key: google-sql-db-instance
            - name: GOOGLE_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: rtmis
                  key: google-project
          volumeMounts:
            - name: rtmis-secrets
              mountPath: "/secrets/cloudsql/credentials.json"
              subPath: rtmis-service-account.json
              readOnly: true
        - name: backend
          image: eu.gcr.io/akvo-lumen/rtmis/backend:${CI_COMMIT}
          ports:
            - containerPort: 8000
          env:
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: db-schema
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: db-password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: db-host
            - name: DJANGO_SECRET
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: django-secret
            - name: MAILJET_APIKEY
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: mailjet-apikey
            - name: MAILJET_SECRET
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: mailjet-secret
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: email-from
            - name: WEBDOMAIN
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: webdomain
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: sentry-dsn
            - name: PROD
              value: "TRUE"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/credentials.json
            - name: STORAGE_PATH
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: storage-path
            - name: APK_UPLOAD_SECRET
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: apk-upload-secret
          readinessProbe:
            httpGet:
              path: /api/v1/health/check
              port: 8000
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /api/v1/health/check
              port: 8000
            initialDelaySeconds: 30
          volumeMounts:
            - name: rtmis-secrets
              mountPath: /secrets/credentials.json
              subPath: rtmis-service-account.json
              readOnly: true
            - name: nfs-pvc
              mountPath: "/app/storage"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
        - name: worker
          image: eu.gcr.io/akvo-lumen/rtmis/worker:${CI_COMMIT}
          env:
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: db-schema
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: db-password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: db-host
            - name: DJANGO_SECRET
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: django-secret
            - name: MAILJET_APIKEY
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: mailjet-apikey
            - name: MAILJET_SECRET
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: mailjet-secret
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: email-from
            - name: WEBDOMAIN
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: webdomain
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: sentry-dsn
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/credentials.json
            - name: STORAGE_PATH
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: storage-path
            - name: APK_UPLOAD_SECRET
              valueFrom:
                secretKeyRef:
                  name: rtmis
                  key: apk-upload-secret
          volumeMounts:
            - name: rtmis-secrets
              mountPath: /secrets/credentials.json
              subPath: rtmis-service-account.json
              readOnly: true
            - name: nfs-pvc
              mountPath: "/app/storage"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
      volumes:
        - name: rtmis-secrets
          secret:
            secretName: rtmis
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: rtmis
